inherit_from:
  - /workspace/local_dataset/SceneGraphFusion_code/3DSSG/configs/dataset/config_base_3RScan_full_l160.yaml
  - /workspace/local_dataset/SceneGraphFusion_code/3DSSG/configs/method/config_base_3DSSG.yaml

SEED: 2021
VERBOSE: false
GPU: [0]

training:
  out_dir: /workspace/local_dataset/3DSSG_staged/checkpoint

eval:
  mode: segment
  data_workers: 0
  topK: 10

logging:
  method: none

wandb:
  dry_run: true

model:
  multi_rel: true

data:
  path_3rscan: /workspace/local_dataset/3DSSG_internal_dev_staged/runtime
  path_3rscan_data: /workspace/local_dataset/3DSSG_internal_dev_staged/runtime/raw_dev
  path_file: /workspace/local_dataset/3DSSG_internal_dev_staged/runtime/files
  path_split: /workspace/local_dataset/3DSSG_internal_dev_staged/runtime/files/cvpr
  path: /workspace/local_dataset/3DSSG_internal_dev_staged/preprocessed/3RScan_3RScan160
  path_gt: /workspace/local_dataset/3DSSG_internal_dev_staged/preprocessed/3RScan_3RScan160
  path_image_feature: /workspace/local_dataset/3DSSG_internal_dev_staged/runtime/image_features
  roi_img_path: /workspace/local_dataset/3DSSG_internal_dev_staged/runtime/roi_gt
  load_cache: false
  load_images: false
  load_points: true
  sample_in_runtime: true
  data_augmentation: false
  max_num_edge: -1
  drop_edge_eval: 0
